# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_type', models.CharField(max_length=200)),
                ('report_type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('registration', models.CharField(max_length=200)),
                ('craft_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=8)),
                ('airport_name', models.CharField(max_length=200)),
                ('operator_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm_type', models.CharField(choices=[('0', 'universal'), ('1', 'thrift'), ('2', 'rural')], max_length=1)),
                ('location', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('fs_type', models.CharField(max_length=200)),
                ('implementing_office', models.CharField(max_length=200)),
                ('contractor', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
    ]
